# Generated by Django 3.2.5 on 2021-07-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_slots_booking_table_slot_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
