# Generated by Django 3.2.5 on 2021-07-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_delete_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking_spaces',
            name='slot_booking',
        ),
        migrations.AddField(
            model_name='slots_booking_table',
            name='parking_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.parking_spaces'),
        ),
    ]
