# Generated by Django 3.2.5 on 2021-07-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
